import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// import TMSLandingPage from "@/components/TMSLandingPage";
// OR
import LandingPage from "@/components/landing2";
import Navbar from "@/components/appbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "ticketing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="p-4 border-b mb-4">
          {" "}
          <Navbar />{" "}
        </div>

        {/* <TMSLandingPage /> */}
        {/* <LandingPage /> */}
        {children}
      </body>
    </html>
  );
}
